builds:
  - env:
      - CGO_ENABLED=0
      - GOPROXY="https://goproxy.cn,direct"
    goarch:
      - amd64
      - arm64
    goos:
      - linux
    flags:
      - -trimpath
    ldflags:
      - -s -w
    main: ./cmd

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  use: gitlab
  groups:
    - title: Features
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 100
    - title: 'Bug fixes'
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 200
    - title: 'Documentation updates'
      regexp: "^.*docs[(\\w)]*:+.*$"
      order: 400
    - title: Others
      order: 999
  filters:
    exclude:
      - '^test:'
      - '^chore'
      - 'merge conflict'
      - '^ci'
      - '^style'
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch